### ISSUE TITLE
Fatal error: Class 'GuzzleHttp\Psr7\Response' not found

### ISSUE THREAD

**Issue by speich** [vitec-memorix/OaiPmh#7]
ResponseDocument.php uses class GuzzleHttp\Psr7\Response but you give example with zend diactoros in readme. It would be helpful if this dependency was mentioned (or removed).

Line 6 should be replaced with `use Zend\Diactoros\Response\TextResponse;`

**Comment by ramonfincken** [comment]
Updated -> https://github.com/kennisnet/WP-plugin-OAIPMH
https://github.com/kennisnet/WP-plugin-OAIPMH/blob/master/public/partials/public-display.php

**Comment by Pin0** [comment]
Closed for we are no longer actively maintaining this repository.
